# Generated by Django 5.2.1 on 2025-06-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_posts', '0009_likedcomment_comment_lkies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='lkies',
            new_name='likes',
        ),
    ]
